"""initial schema

Revision ID: 2e163cb6e5a8
Revises: 
Create Date: 2026-06-29 22:48:20.010754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e163cb6e5a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('ongoing', sa.Boolean(), nullable=True),
    sa.Column('impacted_agencies', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('badge', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_issues',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('agency', sa.String(length=120), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=True),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.Column('age', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cat', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('v', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('providers',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('country', sa.String(length=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('agencies',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('provider_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('pcc', sa.String(length=8), nullable=False),
    sa.Column('gds', sa.String(length=4), nullable=False),
    sa.Column('country', sa.String(length=4), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('used_seats', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('month_adms', sa.Integer(), nullable=True),
    sa.Column('last_active', sa.String(length=40), nullable=True),
    sa.Column('policy_level', sa.String(length=40), nullable=True),
    sa.Column('admin_email', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agencies_provider_id'), ['provider_id'], unique=False)

    op.create_table('escalations',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('provider_id', sa.String(length=20), nullable=False),
    sa.Column('agency', sa.String(length=120), nullable=True),
    sa.Column('pnr', sa.String(length=20), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('opened', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('sla', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('escalations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escalations_provider_id'), ['provider_id'], unique=False)

    op.create_table('threads',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('provider_id', sa.String(length=20), nullable=False),
    sa.Column('agency', sa.String(length=120), nullable=True),
    sa.Column('agent', sa.String(length=80), nullable=True),
    sa.Column('unread', sa.Integer(), nullable=True),
    sa.Column('last', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threads_provider_id'), ['provider_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('provider_id', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('mfa', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vouchers',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('provider_id', sa.String(length=20), nullable=False),
    sa.Column('pax', sa.String(length=120), nullable=True),
    sa.Column('pnr', sa.String(length=20), nullable=True),
    sa.Column('ticket', sa.String(length=40), nullable=True),
    sa.Column('reason', sa.String(length=80), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('payment', sa.String(length=20), nullable=True),
    sa.Column('card', sa.String(length=40), nullable=True),
    sa.Column('policy', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('issued', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vouchers_provider_id'), ['provider_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.String(length=20), nullable=True),
    sa.Column('actor_user_id', sa.String(length=20), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=40), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_provider_id'), ['provider_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(length=20), nullable=False),
    sa.Column('sender', sa.String(length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('t', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_thread_id'), ['thread_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_thread_id'))

    op.drop_table('messages')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_provider_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vouchers_provider_id'))

    op.drop_table('vouchers')
    op.drop_table('users')
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threads_provider_id'))

    op.drop_table('threads')
    with op.batch_alter_table('escalations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escalations_provider_id'))

    op.drop_table('escalations')
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agencies_provider_id'))

    op.drop_table('agencies')
    op.drop_table('providers')
    op.drop_table('policy_docs')
    op.drop_table('pending_issues')
    op.drop_table('learning_modules')
    op.drop_table('alerts')
    # ### end Alembic commands ###
