"""section6: updated_at, last_login_at, sla_due_at

Revision ID: 888a60e94a0c
Revises: 926048a19b22
Create Date: 2026-06-30 21:59:37.795175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888a60e94a0c'
down_revision = '926048a19b22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('escalations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sla_due_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login_at')

    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('escalations', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('sla_due_at')

    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
