"""users: add reset_token, reset_expires

Revision ID: 926048a19b22
Revises: 2e163cb6e5a8
Create Date: 2026-06-30 00:18:19.441589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926048a19b22'
down_revision = '2e163cb6e5a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('reset_expires', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_reset_token'), ['reset_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_reset_token'))
        batch_op.drop_column('reset_expires')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
